### ISSUE TITLE
Add link to Github repository @ https://opensource.mercedes-benz.com/manifesto/

### ISSUE THREAD

**Issue by berendt** [mercedes-benz/mercedes-benz-foss-manifesto#4]
Via the Manifesto.pdf @ https://opensource.mercedes-benz.com/manifesto/ you can't find this repository at the moment. Please add a link there as well.

**Comment by berendt** [comment]
I mean in the PDF. Not on the page itself.

**Comment by wgehring** [comment]
Good hint - thanks for the feedback! We'll get on it.

**Comment by Nicson387** [comment]
Hey berendt, thanks for your feedback! We added the link to both PDFs and implemented them to the FOSS landing page :-)
