### ISSUE TITLE
Add license to @ https://opensource.mercedes-benz.com/manifesto/

### ISSUE THREAD

**Issue by berendt** [mercedes-benz/mercedes-benz-foss-manifesto#5]
On https://opensource.mercedes-benz.com/manifesto/ is currently not deposited which license the manifest has. It makes sense to store this directly there to make it visible.

**Comment by wgehring** [comment]
Thanks for pointing this out! You are right, it does make sense. We'll add it.

**Comment by berendt** [comment]
Please also in the Manifesto.PDF.

**Comment by Nicson387** [comment]
Hey berendt, thanks for your feedback here as well! We also added the name of the license and a link into both PDFs.
