### ISSUE TITLE
Remove the pirate-style Manifesto

### ISSUE THREAD

**Issue by berendt** [mercedes-benz/mercedes-benz-foss-manifesto#6]
A document named pirate-style.pdf is currently available on https://opensource.mercedes-benz.com/manifesto/.

What is this statement? That FOSS has something to do with piracy? I do not feel that and would prefer it if it were removed. FOSS has exactly nothing to do with piracy.

Wikipedia (https://en.wikipedia.org/wiki/Piracy):

> Piracy is an act of [robbery](https://en.wikipedia.org/wiki/Robbery) or [criminal](https://en.wikipedia.org/wiki/Crime) [violence](https://en.wikipedia.org/wiki/Violence) by [ship](https://en.wikipedia.org/wiki/Ship) or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable goods. Those who conduct acts of piracy are called pirates, while the dedicated ships that pirates use are called pirate ships.

**Comment by wgehring** [comment]
You are right. FOSS has nothing to do with piracy at all. This is just a fun thing. 
If it provokes this kind of connotation, however, it is absolutely and completely unintended. Perhaps we should rename it then to "old parchment-style" or similar. I will follow-up on this.

**Comment by berendt** [comment]
It's clear that it's about the style itself and not about saying that FOSS is piracy ;)

But in the place of a manifesto, I would be super careful with the filenames here. In the end you read ``Pirate`` together with ``FOSS``. At least that's what I stumbled upon.

**Comment by wgehring** [comment]
We have replaced all the "pirate" wordings with neutral ones (e.g. "old parchment-style", here in the repo as well as on the landing page https://opensource.mercedes-benz.com/manifesto/   :-)
