### ISSUE TITLE
Add Template Manifesto

### ISSUE THREAD

**Issue by berendt** [mercedes-benz/mercedes-benz-foss-manifesto#7]
We would like to adopt the manifesto 1:1. I think it makes sense to store a template version or generic version that can be copied directly. Similar to e.g. the ASL 2.0.

Something like this:

```
{name of company} FOSS Manifesto

## Preamble ##

### The {name of company}, ####
```

**Comment by wgehring** [comment]
Yes, that is a good idea as well! Thank you. We'll get on it (but give us a few days).

Great news to hear that you consider adopting the FOSS Manifesto, too. :-)
